package mdp.SI5b.Pahlawanku;

import java.util.ArrayList;

public class DataStasiun {
    public static String[][] data = new String[][]{
            {"Mojiko Station", "Stasiun dibuka pada 1 April 1891, Dengan privatisasi Kereta Api Nasional Jepang(JNR) pada 1 April 1987, stasiun tersebut berada di bawah kendali JR Kyusu. Sejak 29 September 2012, gedung stasiun antuk tahun 1914 ditutup sementara untuk renovasi besar-besaran. Dijadwalkan kembali untuk dibuka kembali pada Maret 2018. itu dibuka kembali pada tahun 2019 dan merupakan salah satu dari dua stasiun kereta api yang ditetapkan sebagai properti budaya penting", "https://media.japanesestation.com/images/750x422/2020/07/05/72862-stasiun-jr-mojiko.jpg","2-5 Nishi-Kaigan, Moji-ku ward, Kitakyushu city, Fukuoka Prefecture Japan","33.945325688802484, 130.96157365570434"},
            {"Tokyo Station", "Stasiun Tokyo adalah stasiun kereta api di Chiyoda, Tokyo, Jepang. Stasiun aslinya terletak di distrik bisnis Marunoiichi Chiyoda di dekat halaman Istana Kekaisaran. Perpanjangan Timur yang lebih baru tidak jauh dari distrik komersial Ginza. Karena luasnya area yang dicakup oleh stasiun, stasiun ini dibagi menjadi sisi Marunouchi (barat) dan Yaesu (timur) dalam petunjuk arahnya. Dilayani oleh jalur kereta berkecepatan tinggi dari jaringan Shinkansen, Stasiun Tokyo adalah terminal kereta api antar kota utama di Tokyo. Ini adalah stasiun tersibuk di Jepang, dengan lebih dari 4.000 kereta datang dan berangkat setiap hari, dan tersibuk kelima di Jepang Timur dalam hal jumlah penumpang rata-rata, lebih dari 500.000 orang menggunakan Stasiun Tokyo setiap hari Stasiun ini juga dilayani oleh banyak jalur komuter regional Japan Railways, serta jaringan Tokyo Metro.", "https://media.japanesestation.com/images/652x367/2020/07/05/63590-tokyo-station.jpg","Chiyoda, Tokyo, Japan", "35.68147147839047, 139.7671033403936"},
            {"Enoden Station (\"kamakuro Koko Mae\")", "Stasiun Enoden adalah stasiun kereta api komuter di Enoshima Electric Railway (Enoden), yang terletak di lingkungan Koshigoe di kota Kamakura, Prefektur Kanagawa, Jepang. Meskipun ukurannya kecil, tempat ini terkenal akan keindahan pemandangannya, karena pemandangan Samudra Pasifik dan Gunung Fuji terbuka dari peron stasiun.Stasiun Kamakurakōkōmae dibuka pada 20 Juni 1903 sebagai Stasiun Hisaka. Itu berganti nama menjadi namanya yang sekarang pada 20 Agustus 1953. Pada tahun 1997, itu terpilih sebagai salah satu dari 100 Stasiun Teratas di Wilayah Kantō  oleh panitia seleksi yang ditugaskan oleh Kementerian Perhubungan Jepang.", "https://resources.matcha-jp.com/archive_files/jp/2016/06/DSCF5984-1024x682.webp", "Kamakura bersama Fujisawa Station di Fujisawa, Kanagawa","35.31124904537315, 139.4873736692559"},
            {"Kareigawa Station", "Stasiun Kareigawa adalah stasiun kereta api di Jalur Hisatsu di Kirishima, Kagoshima, Jepang, yang dioperasikan oleh Perusahaan Kereta Api Kyushu (JR Kyushu). Stasiun dibuka pada tahun 1903.", "https://media.japanesestation.com/images/652x367/2020/07/05/11470-stasiun-kareigawa.jpg", "Hisatsu Line di Kirishima, Kagoshima, Japan", "31.82713120498892, 130.72315424032192"},
            {"Otaru Station", "Stasiun Otaru adalah stasiun kereta api di Otaru, Hokkaido, Jepang, yang dioperasikan oleh Perusahaan Kereta Api Hokkaido (JR Hokkaido). Itu diberi nomor \"S15\". Stasiun Otaru dibuka pada 28 Juni 1903. Nama stasiun ini awalnya adalah Stasiun Otaru Chūō Nama ini diubah pada 15 Oktober 1904 menjadi Stasiun Takashima , pada 15 Desember 1905 menjadi Stasiun Chūō Otaru dan pada 15 Juli 1920 hingga sekarang. Dari 11 Juni 1900 hingga 14 Juli 1920, Stasiun Minami-Otaru saat ini disebut Stasiun Otaru.", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Otaru_Station%2C_Otaru%2C_Hokkaido_on_July_19th%2C_2018.jpg/300px-Otaru_Station%2C_Otaru%2C_Hokkaido_on_July_19th%2C_2018.jpg","Otaru, Hokkaido, Japan", "43.19790935333175, 140.99367976939445"},
            {"Nikko Station", "Stasiun Nikkō adalah stasiun kereta api di kota Nikkō, Tochigi, Jepang, yang dioperasikan oleh East Japan Railway Company (JR East). Stasiun Nikkō dibuka pada 1 Agustus 1890. Dengan privatisasi Kereta Api Nasional Jepang (JNR) pada 1 April 1987, stasiun ini berada di bawah kendali JR East.", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/JRE_Nikko-STA.jpg/300px-JRE_Nikko-STA.jpg", "the city of Nikkō, Tochigi, Japan", "36.74761131911373, 139.62199678274303"},
            {"Harajuku Station", "Stasiun Harajuku adalah stasiun kereta api di Shibuya, Tokyo, Jepang, yang dioperasikan oleh East Japan Railway Company (JR East). Nama stasiun ini diambil dari kawasan di sisi timurnya, Harajuku. Stasiun dibuka pada 30 Oktober 1906.Pintu tepi platform dipasang di platform pada November 2014, dan dioperasikan mulai Desember. Pada bulan Juni 2016, JR East mengumumkan rencana untuk membangun kembali stasiun menjelang Olimpiade 2020 untuk mengurangi kepadatan. Sebuah gedung stasiun baru akan dibangun oleh JR East di pintu masuk stasiun Meiji-Jingu. Peron sementara yang digunakan selama periode sibuk akan menjadi peron permanen untuk kereta api yang menuju ke utara melalui stasiun. Gedung dan peron stasiun baru dibuka pada 21 Maret 2020, bertepatan dengan Olimpiade dan Paralimpiade Tokyo. JR East memutuskan pada November 2019 untuk menghancurkan gedung stasiun lama di pintu masuk Takeshita dengan alasan keamanan setelah Paralimpiade, dan menggantinya dengan struktur yang lebih aman yang dibangun dengan gaya serupa.", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Harajuku_Station_200321a2.jpg/300px-Harajuku_Station_200321a2.jpg","Shibuya, Tokyo, Japan","35.6703166953052, 139.7024447403934"},
            {"Todoroki Station", "Stasiun Todoroki adalah stasiun kereta api di Jalur Tokyu Oimachi di barat daya Tokyo, Jepang, yang dioperasikan oleh operator kereta api swasta Tokyu Corporation. Stasiun dibuka pada tanggal 1 November 1929", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Todoroki_Station_July_4_2020_various_17_32_49_298000.jpeg/300px-Todoroki_Station_July_4_2020_various_17_32_49_298000.jpeg", "the Tokyu Oimachi Line di southwest Tokyo, Japan", "35.60851441161825, 139.64812564224434"},
            {"Gujō-Hachiman Station","Stasiun Gujō-Hachiman adalah stasiun kereta api di kota Gujō, Prefektur Gifu, Jepang, yang dioperasikan oleh operator kereta api sektor ketiga Nagaragawa Railway. Stasiun Gujō-Hachiman dibuka pada 8 Desember 1929. Operasi dipindahkan dari Japan National Railway (JNR) ke Nagaragawa Railway pada 11 Desember 1986.","https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Guj%C5%8D-hachiman_Station.jpg/300px-Guj%C5%8D-hachiman_Station.jpg", "the city of Gujō, Gifu Prefecture, Japan", "35.74204480200529, 136.94741678457504"},
            {"Muroran Station","Stasiun Muroran adalah stasiun kereta api di Jalur Utama Muroran di Muroran, Hokkaido, Jepang, yang dioperasikan oleh Perusahaan Kereta Api Hokkaido (JR Hokkaido). Stasiun dibuka pada 1 Juli 1897. Dengan privatisasi Kereta Api Nasional Jepang (JNR) pada 1 April 1987, stasiun tersebut berada di bawah kendali JR Hokkaido. Stasiun dipindahkan ke lokasinya saat ini, 1,1 km lebih dekat ke Higashi-Muroran, pada 1 Oktober 1997.","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Muroran_station_20170709.jpg/300px-Muroran_station_20170709.jpg", "Muroran Main Line di Muroran, Hokkaido, Japan", "42.318231306571235, 140.9742964386851"}
    };

    public static ArrayList<ModelStasiun> ambilDataStasiun(){
        ArrayList<ModelStasiun> dataStasiun = new ArrayList<>();

        for(String[] varData: data){
            ModelStasiun mdl = new ModelStasiun();
            mdl.setNama(varData[0]);
            mdl.setTentang(varData[1]);
            mdl.setFoto(varData[2]);
            mdl.setAlamat(varData[3]);
            mdl.setKoordinat(varData[4]);

            dataStasiun.add(mdl);
        }
        return dataStasiun;
    }
}
